### PR TITLE
add star buyer's guide and tabbed layout

### PR DESCRIPTION
**Pull request by matildepark**
- Tweaks headers and footers to be vertically aligned (specifically the "urbit.org" + arrow was a little off)
- Removes star.market from homepage
- Updates markdown component to use same pipeline as urbit.org (for our inline HTML)
- adds Star Buyer's Guide (all the inline HTML itself an advertisement for markdown -> react componentisation)
- adds a general tabbed layout component to the guides template
- I also noticed that the star operator's guide is not accessible on the site normally; even then, the [production deployed version is oversized](https://operators.urbit.org/guides/running-a-star). I corrected this in this PR to make it look presentable, but it's only accessible via our guide here.

~~The tabbed layout component has a few tradeoffs due to the fact that we compile all our Markdown to HTML directly; we can't manipulate that HTML client-side based on URL queries, so we, client-side, hide all other sections on the same page based on the current URL query. It can only does this if it sees the DOM and the react-router has instantiated, so it means the rendering layer can't be itself entirely hidden to parse which section to render. This means it produced a slight flicker after load, so I compensated by adding a `ready` check to keep the pages in DOM but not seen, meaning these pages have a 100ms delay on render other pages don't. I think this is an acceptable compromise, though it's worth reconsidering another approach for this that isn't client-side if possible. Not sure at present.~~ We use `next/link` for the navigation and it hides the flicker now.

Also the link callouts on the main page don't highlight on hover because they're being overwritten by our markdown CSS, which aggressively undoes a lot of the site's display-oriented styling. In general, we shouldn't be mixing that content with the Markdown content, but Markdoc should address that in future.

PR approval and merge pending copyediting phase.

### CODE REVIEW

**Comment by gordoncc** [comment]
Great initial build.  Just a few things.

1. **Guide Homepage**
Let's update the guide homepage to reflect this design for the link to the Stars Buyer's Guide.

Screen Shot 2022-05-26 at 5 33 12 PM

2.  **Images**
- Images are appearing low resolution when full screen, so let's set that column so that's it's 3/4 width or so on desktop layout
- Some of the images that aren't full screenshots I've placed in frames labeled IMG within Figma.  We can use those frames to export those particular images so that they don't appear overly large within the column.  I've gone ahead and re-exported all the images including their frames so that they have the correct ratio and position.  You can find them in media.urbit.org/operators/star-buyers

**Comment by gordoncc** [comment]
3. **Section Links**
Updated overview page link design to be more link-like

Screen Shot 2022-05-27 at 1 31 59 PM

**Comment by matildepark** [comment]
All changes addressed; note well that for some inexplicable reason this site supports dark mode, and your images aren't transparent. I made our svgs invert on dark mode so that they match better.

**Comment by gordoncc** [comment]
Nice work on the updates.  I think we just need to add about 50px of padding between those tabbed links to match the design and we're good from a layout perspective.
Screen Shot 2022-06-06 at 11 33 50 AM

Thanks for noting the dark mode feature on this site.  I do like dark mode so if we make that a standard thing then I can be persuaded to change the images to .pngs.

**Comment by matildepark** [comment]
I mean, I didn’t just decide to add dark mode here. It was here to begin with. So I don’t really know what you’re asking me to do. Rip it out of the site? Introduce it everywhere? Massive overhead rather than just giving me transparent images.

**Comment by jalehman** [comment]
I kind of think the Star Buyer's Guide should feature more prominently on this page. It's much more useful content than any of what's in the current Getting Started section, and lends context to the Marketplaces.

**Comment by gordoncc** [comment]
> I mean, I didn’t just decide to add dark mode here. It was here to begin with. So I don’t really know what you’re asking me to do. Rip it out of the site? Introduce it everywhere? Massive overhead rather than just giving me transparent images.

Not asking anything.  Just keeping it in mind as a feature that we could have as part of the upcoming redesign efforts.

Agree that transparent images would be a nice touch here, was thinking of images globally.

**Comment by matildepark** [comment]
Should be good to go?

**Comment by jalehman** [comment]
Looks good to me. @gordoncc ?

**Comment by matildepark** [comment]
The images are still gonna look bad on the dark mode site though.

**Comment by matildepark** [comment]
I mean, I didn’t just decide to add dark mode here. It was here to begin
with. So I don’t really know what you’re asking me to do. Rip it out of the
site? Introduce it everywhere? Massive overhead rather than just giving me
transparent images.

**Pull request merged**
